### ISSUE TITLE
ERC tokens standard

### ISSUE THREAD

**Issue by khemiriwalid** [OffcierCia/DeFi-Developer-Road-Map#20]
Tokens are the basic building block of this new ecosystem. All DeFi protocols use the ERC token standard.
Most decentralized applications will be needed to interact with DeFi protocols like Uniswap, Balancer, etc and this interaction will be based on those ERC standards.
So, the developers need to know those ERC token standard in order to be able to build those new types of application.
The chart must include at least  ERC20, ERC721, ERC1155 tokens standard.
I think we can put them the Ethereum part of the chart.

**Comment by OffcierCia** [comment]
Thank you! Added it to roadmap
