### ISSUE TITLE
Chains and layer 2 solutions

### ISSUE THREAD

**Issue by khemiriwalid** [OffcierCia/DeFi-Developer-Road-Map#21]
Most DeFi protocols are deployed on Ethereum and Binance Smart Chain (BSC) chains. 
Also Polygon (Previously Matic Network) becomes a popular chain and it is used by multiple DeFi protocols.
There are multiple layer 2 solution, I think that the roadmap should list them.
I think that the chain section can be like that:

![chain part 1 0](https://user-images.githubusercontent.com/29165820/124043943-190def00-da04-11eb-9c5d-ccf5f7edb124.png)

**Comment by OffcierCia** [comment]
This information is in the guide under the roadmap, I do not think there is any point in specifying it cause L2 and SideChains section already exists

**Comment by OffcierCia** [comment]
Added one more section with mentioning BSC/Polygon, thank you

**Comment by OffcierCia** [comment]
+ Added L2 table

**Comment by OffcierCia** [comment]
[![sc8.png](https://i.postimg.cc/Gt3y5yLW/sc8.png)](https://postimg.cc/MM4HcXj5)
