### ISSUE TITLE
Suggestion: change "DeFi implementation" with "DeFi services"

### ISSUE THREAD

**Issue by khemiriwalid** [OffcierCia/DeFi-Developer-Road-Map#22]
DeFi protocols provide multiple services like decentralized exchange, lending & borrowing, stablecoin, etc.
We will use multiple DeFi  services in order to build advanced use cases. 

Example : 
- A DeFi application named "X" need to use a service from other DeFi application named "Y" ("Y" has a token named "Y token" used to consume their services ). 
- In the smart contract of "X" , there is a code that check if they have sufficient  amount of 'Y token' before call "Y" services.
- If the contract doesn't have the amount of tokens to consume "Y" service, they will use one of the decentralized exchanges like Uniswap, Balancer, Curve to swap some amount of their ETH to "Y token" in order to complete the execution of a such business logic.

So, I suggest to list the generic services provided by DeFi protocols like decentralized exchange, lending and borrowing and their famous and mass adapted protocols. Because, developers need to know those generic protocols and how to call them with smart contract code (API of each protocol).

![DeFi services](https://user-images.githubusercontent.com/29165820/124200462-54282500-dacd-11eb-8084-c5032268ff5a.png)

**Comment by OffcierCia** [comment]
Will add new info to table today, thank you so much!
