### ISSUE TITLE
Modern Finance Resources

### ISSUE THREAD

**Issue by pmuens** [OffcierCia/DeFi-Developer-Road-Map#26]
Maybe we can add some resources about Modern Finance from the realm of Options, Futures, Derivatives, etc. (kind of Financial Engineering related).

I don't have any resources like that myself but it would be great to have something handy which teaches you the basics of financial theories you'd deal with when building in DeFi. Should be lightweight reads, though.

**Comment by OffcierCia** [comment]
+ Will take a look, thank you!

**Comment by pmuens** [comment]
Awesome! Thanks for looking into it 👍
