### ISSUE TITLE
Read this article (Smart Contract session) link dead

### ISSUE THREAD

**Issue by wyushi** [OffcierCia/DeFi-Developer-Road-Map#60]
Read this article (Smart Contract session) link dead
```
- Read [this article](https://blog.zeppelin.solutions/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05)
```

**Comment by OffcierCia** [comment]
Hi! see https://blog.openzeppelin.com/the-hitchhikers-guide-to-smart-contracts-in-ethereum-848f08001f05/, https://members.delphidigital.io/reports/the-hitchhikers-guide-to-ethereum/, https://share.summari.com/the-hitchhikers-guide-to-smart-contracts-in-ethereum and I saved a webpagee for ya.  https://drive.google.com/file/d/1HEZRKfaQH_8Y0XglHUJJRREJbzTQ0C8b/view?usp=sharing + fixed
