### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by ndsvw** [OffcierCia/DeFi-Developer-Road-Map#91]
Hello, I found some broken hyperlinks:
- [ ] https://www.wenyanet.com/opensource/ja/6304f1549168d4612c5c5064.html (file: README.md, error: CERT_HAS_EXPIRED)
- [ ] https://blog.praneethreddy.me/ultimate-roadmap-for-web3-developers-from-zero-to-master?deviceType=desktop (file: README.md, error: ENOTFOUND)
- [ ] https://directroute.nodereal.io (file: README.md, error: ENOTFOUND)
- [ ] https://swarm-gateways.net/ (file: README.md, error: EAI_AGAIN)
- [ ] https://faucets.blockxlabs.com/ (file: README.md, error: ENOTFOUND)
- [ ] https://components.bounties.network (file: README.md, error: EAI_AGAIN)
- [ ] https://simpleaswater.com/defi/#analytics (file: README.md, error: EAI_AGAIN)
- [ ] https://github.com/sambacha/art-of-engineering/blob/master/ENGINEERING_ART_OF.md (file: README.md, status code: 404)
- [ ] https://bridge.poa.net/ (file: README.md, error: ENOTFOUND)
- [ ] https://eth2stats.io/ (file: README.md, error: ENOTFOUND)
- [ ] https://docs.ethhub.io/ethereum-roadmap/ethereum-2.0/eth-2.0-phases/ (file: README.md, error: ENOTFOUND)
- [ ] https://docs.ethhub.io/ethereum-roadmap/ethereum-2.0/eth2.0-teams/teams-building-eth2.0/ (file: README.md, error: ENOTFOUND)
- [ ] https://eth2-fork-mon.stokes.io/ (file: README.md, error: ENOTFOUND)
- [ ] https://rekt.eth.link/leaderboard (file: README.md, status code: 404)
- [ ] https://github.com/openblocksec/blocksec-incidents (file: README.md, status code: 404)
- [ ] https://ethstats.io (file: README.md, error: ECONNRESET)
- [ ] https:/solidity-by-example.org (file: README.md, status code: 400)
- [ ] https://txpool.zengo.com/ (file: README.md, status code: 503)
- [ ] https://ethcontract.watch (file: README.md, error: ENOTFOUND)
- [ ] https://oracles.club (file: README.md, error: ENOTFOUND)
- [ ] https://securify.chainsecurity.com/ (file: README.md, error: ENOTFOUND)
- [ ] https://tool.smartdec.net/ (file: README.md, error: ENOTFOUND)
- [ ] https://piet.slock.it (file: README.md, status code: 503)
- [ ] https://walletconnect.org/ (file: README.md, status code: 404)
- [ ] https://github.com/mesg-foundation/service-ethereum-contract (file: README.md, status code: 404)
- [ ] https://github.com/mesg-foundation/service-ethereum (file: README.md, status code: 404)
- [ ] https://marmo.io/ (file: README.md, status code: 404)
- [ ] https://getdoppelganger.io/ (file: README.md, error: ENOTFOUND)
- [ ] https://blockchair.com/bitcoin/address/17Ydx9m7vrhnx4XjZPuGPMqrhw3sDviNTU (file: README.md, error: ECONNRESET)

**Comment by OffcierCia** [comment]
Thank you! Gonna fix ASAP

**Comment by OffcierCia** [comment]
@SvenMeyer just fixed, FYI: officercia.mirror.xyz/p1ieZdxQWH4yHCNOXNPHyT8So1cY0X_wMGKwdmavi7s
