### ISSUE TITLE
Files names conflict

### ISSUE THREAD

**Issue by tvcapital** [OffcierCia/DeFi-Developer-Road-Map#93]
When I clone the repo to my macbook I get this error about conflicting names README_Tel.md and README_tel.md: 

```
warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) 
and only one from the same colliding group is in the working tree:

  'translations/README_Tel.md'
  'translations/README_tel.md'
```

And because of this collision these files become marked as changed by git. 

Also, when I try to create pull request I got this error:

```
admin$ git push origin main
remote: Permission to OffcierCia/DeFi-Developer-Road-Map.git denied to tvcapital.
fatal: unable to access 'https://github.com/OffcierCia/DeFi-Developer-Road-Map.git/': The requested URL returned error: 403

```

**Comment by OffcierCia** [comment]
Hello! Just fixed! @tvcapital thank you for heads up!

Feel free to DM me in Telegram - https://t.me/farm42 and please try creating a pull request one more time!
